spring:
  datasource:
    platform: h2
    url: "jdbc:h2:./soaps"
  jpa:
    database-platform: H2

spring.jpa.hibernate.ddl-auto: update

server:
  port: 16480
  address: 127.0.0.1

server.undertow.accesslog.dir: logs
server.undertow.accesslog.enabled: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

